-- ***********************************************
-- Master/Task:CHG0034048/CTASK0022610
-- Site       :AU
-- Developer  :Ashley Gilliam
-- Clone      :AUFDEV2
-- Date       :7/03/2019
-- ***********************************************

SET FEEDBACK ON
SET LINESIZE 300
SET SERVEROUTPUT ON

SELECT name FROM v$database;

CREATE TABLE PS_BOR_CUSTDL_RPT (BUSINESS_UNIT VARCHAR2(5) NOT NULL,
   FUND_CODE VARCHAR2(5) NOT NULL,
   DEPTID VARCHAR2(10) NOT NULL,
   PROJECT_ID VARCHAR2(15) NOT NULL,
   ACCOUNT VARCHAR2(10) NOT NULL,
   BEGIN_BALANCE DECIMAL(26, 3) NOT NULL,
   ADD_AMOUNT DECIMAL(26, 3) NOT NULL,
   REDUCTIONS_AMOUNT DECIMAL(26, 3) NOT NULL) TABLESPACE PTRPTS
 STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE
 0) PCTFREE 10 PCTUSED 80
/
CREATE TABLE PS_BOR_RUN_CNTL_CF (OPRID VARCHAR2(30) NOT NULL,
   RUN_CNTL_ID VARCHAR2(30) NOT NULL,
   BUSINESS_UNIT VARCHAR2(5) NOT NULL,
   FISCAL_YEAR SMALLINT NOT NULL,
   BOR_CFRPT_DPTPRJ60 VARCHAR2(1) NOT NULL,
   BOR_CFRPT_EXINAC60 VARCHAR2(1) NOT NULL,
   BOR_CFRPT_DPTPRJ61 VARCHAR2(1) NOT NULL,
   BOR_CFRPT_EXINAC61 VARCHAR2(1) NOT NULL) TABLESPACE PTAPP STORAGE
 (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0)
 PCTFREE 10 PCTUSED 80
/
CREATE UNIQUE INDEX PS_BOR_RUN_CNTL_CF ON PS_BOR_RUN_CNTL_CF (OPRID,
   RUN_CNTL_ID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_BOR_RUN_CNTL_CF NOPARALLEL LOGGING
/
